### ISSUE TITLE
Exception - Class "Redis" not found

### ISSUE THREAD

**Issue by albertolarah** [aws-samples/aws-refarch-moodle#55] opened 2024-01-22 08:40 UTC
The following error appears after installing and enabling the cache

**Comment by vrioux** [comment] 2024-01-25 13:37
Hi, thanks for reporting this issue! We will look at it as soon as possible. Is this a duplicate of https://github.com/aws-samples/aws-refarch-moodle/issues/54 ? Thanks!

**Comment by albertolarah** [comment] 2024-01-25 13:43
Hi @vrioux, In both cases the problem is with the activation of the cache but it is not exactly the same case since one is when Redis is selected and the other is Memcached

**Comment by vrioux** [comment] 2024-01-25 14:10
Thank you for this additional information. Please hold as we look into this. Thanks!

**Comment by vrioux** [comment] 2024-01-30 01:26
Hi @albertolarah, this should be working now if you re-deploy the CloudFormation stack. Please excuse the situation and let me know if you need anything.

**Comment by vrioux** [comment] 2024-01-30 01:26
Closing as fixed.

**Closed as completed by vrioux** 2024-01-30 01:26 UTC
